# Generated by Django 5.2 on 2025-05-15 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='UnknownBrand', max_length=100, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unisex', 'Унисекс')], default='unisex', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Кредитная карта'), ('online', 'Онлайн-оплата')], max_length=50, verbose_name='Метод оплаты'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('added_to_cart_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в корзину')),
                ('ordered', models.BooleanField(default=False, verbose_name='Заказан')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
            },
        ),
    ]
